</$objtype/mkfile

TARG=\
	Markdown\
	Dir\
	Gopher\
	Gemini\

HFILES=config.h

SYSLIB=/sys/lib/richterm
BIN=$SYSLIB/bin/$objtype

</sys/src/cmd/mkmany

RC=\
	richrc\

install:V: bindir $RC

bindir:V:
	mkdir -p $BIN

config.h:
	cp config.def.h config.h

$RC:V:
	mkdir -p $SYSLIB/bin/rc
	for (i in $RC) @{
		cp $i $SYSLIB/bin/rc
	}
