</$objtype/mkfile

TARG=\
	Markdown\
	Dir\
	Gopher\
	Gemini\

SYSLIB=/sys/lib/richterm
BIN=$SYSLIB/bin/$cputype

</sys/src/cmd/mkmany

RC=\
	Handler\

install:V: bindir $RC

bindir:V:
	mkdir -p $BIN

$RC:V:
	mkdir -p $SYSLIB/bin/rc
	for (i in $RC) @{
		cp $i $SYSLIB/bin/rc
	}
